version: '3.8'

services:
  # MSSQL Server container
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-container
    environment:
        SA_PASSWORD: Strong2@PWD12
        ACCEPT_EULA: Y
        MSSQL_PID: Express

  # .NET Core Web API container
  webapi:
    build:
      context: .
      dockerfile: ./Presentation/ProductShop.WebAPI/Dockerfile
    depends_on:
      - mssql
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DbConnectionString: "Server=mssql;User=sa;Password=Strong2@PWD12;TrustServerCertificate=true;"
 