// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductShop.Persistence.DataContexts;

#nullable disable

namespace ProductShop.Persistence.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    partial class ShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductShop.Domain.Entities.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Intel Celeron N4500 Jasper Lake",
                            ImgUri = "https://image.alza.cz/products/NC027p0u0/NC027p0u0.jpg?width=500&height=500",
                            Name = "Acer Aspire 3 ",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 2,
                            Description = "128GB",
                            ImgUri = "https://image.alza.cz/products/RI041b1/RI041b1.jpg?width=500&height=500",
                            Name = "iPhone 14 ",
                            Price = 18990m
                        },
                        new
                        {
                            Id = 3,
                            Description = "20W Charger",
                            ImgUri = "https://image.alza.cz/products/RI012i1b48/RI012i1b48.jpg?width=500&height=500",
                            Name = "Apple 20W USB-C",
                            Price = 589m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Závodní auto McLaren Formule 1",
                            ImgUri = "https://image.alza.cz/products/LO42141/LO42141.jpg?width=500&height=500",
                            Name = "LEGO Technic",
                            Price = 3119m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
